# Generated by Django 5.2.17 on 2026-09-27 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('bot_type', models.CharField(choices=[('UNIFIED', 'Unified Bot'), ('BUYER', 'Buyer / Bidding Bot'), ('SELLER', 'Seller / Registration Bot')], default='UNIFIED', help_text='Role or category of the Telegram bot within this tenant.', max_length=32)),
                ('bot_username', models.CharField(blank=True, help_text='Telegram bot handle without @ (e.g. CygAuctionBot).', max_length=64)),
                ('token_encrypted', models.TextField(blank=True, help_text='Encrypted Telegram bot API token (AES-128-CBC + HMAC-SHA256).')),
                ('token_env_var', models.CharField(blank=True, help_text='Optional environment variable name storing the bot token.', max_length=128)),
                ('webhook_secret_token', models.CharField(blank=True, help_text='Secret token for verifying X-Telegram-Bot-Api-Secret-Token webhook header.', max_length=256)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this bot configuration is active and accepting webhook updates.')),
                ('tenant', models.ForeignKey(help_text='Mandatory explicit foreign key to the owning Tenant.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Telegram Bot Configuration',
                'verbose_name_plural': 'Telegram Bot Configurations',
                'indexes': [models.Index(fields=['tenant', 'is_active', 'bot_type'], name='telegram_en_tenant__645325_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'bot_type'), name='unique_tenant_bot_type')],
            },
        ),
        migrations.CreateModel(
            name='TelegramUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('update_id', models.BigIntegerField(db_index=True, help_text='Telegram update_id delivered by webhook.')),
                ('bot_type', models.CharField(default='UNIFIED', help_text='Bot type through which this update was received.', max_length=32)),
                ('tenant', models.ForeignKey(help_text='Mandatory explicit foreign key to the owning Tenant.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Telegram Update Log',
                'verbose_name_plural': 'Telegram Update Logs',
                'indexes': [models.Index(fields=['tenant', 'update_id'], name='telegram_en_tenant__6927c9_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'update_id'), name='unique_tenant_telegram_update')],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('telegram_user_id', models.BigIntegerField(db_index=True, help_text='Stable numeric Telegram user ID from from_user.id.')),
                ('chat_id', models.BigIntegerField(db_index=True, help_text='Direct Telegram chat ID with this user.')),
                ('username', models.CharField(blank=True, help_text='Telegram @username if set by the user.', max_length=64, null=True)),
                ('first_name', models.CharField(blank=True, default='', help_text='First name from Telegram profile.', max_length=128)),
                ('last_name', models.CharField(blank=True, default='', help_text='Last name from Telegram profile.', max_length=128)),
                ('language_code', models.CharField(blank=True, default='', help_text='IETF language tag reported by Telegram.', max_length=16)),
                ('is_blocked', models.BooleanField(default=False, help_text='Whether the user has blocked the bot or been banned.')),
                ('tenant', models.ForeignKey(help_text='Mandatory explicit foreign key to the owning Tenant.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
                'indexes': [models.Index(fields=['tenant', 'telegram_user_id'], name='telegram_en_tenant__95c33b_idx'), models.Index(fields=['tenant', 'chat_id'], name='telegram_en_tenant__92c093_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'telegram_user_id'), name='unique_tenant_telegram_user')],
            },
        ),
    ]
