# Generated by Django 5.2.17 on 2026-09-27 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_engine', '0001_initial'),
        ('tenants', '0004_remove_tenant_admin_initial_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('bot_type', models.CharField(choices=[('UNIFIED', 'Unified Bot'), ('BUYER', 'Buyer / Bidding Bot'), ('SELLER', 'Seller / Registration Bot')], default='SELLER', help_text='Category of the Telegram bot context.', max_length=32)),
                ('state', models.CharField(choices=[('IDLE', 'Idle'), ('REGISTERING', 'Registering as Seller'), ('CREATING_LISTING', 'Creating Listing'), ('REVIEWING_LISTING', 'Reviewing Listing')], db_index=True, default='IDLE', help_text='Current state in the workflow state machine.', max_length=64)),
                ('step', models.CharField(blank=True, default='', help_text='Current sub-step or questionnaire field.', max_length=64)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='JSON payload storing in-progress form inputs, draft listing IDs, etc.')),
                ('telegram_user', models.ForeignKey(help_text='The Telegram user engaged in this conversation.', on_delete=django.db.models.deletion.CASCADE, related_name='conversation_states', to='telegram_engine.telegramuser')),
                ('tenant', models.ForeignKey(help_text='Mandatory explicit foreign key to the owning Tenant.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Telegram Conversation State',
                'verbose_name_plural': 'Telegram Conversation States',
                'indexes': [models.Index(fields=['tenant', 'telegram_user', 'bot_type'], name='telegram_en_tenant__e8982e_idx'), models.Index(fields=['tenant', 'state'], name='telegram_en_tenant__e6f49d_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'telegram_user', 'bot_type'), name='unique_tenant_user_bot_state')],
            },
        ),
    ]
