# Generated by Django 5.2.17 on 2026-09-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_engine', '0002_telegramconversationstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambotconfig',
            name='access_password',
            field=models.CharField(blank=True, default='', help_text='Password required for user authorization when require_password is True.', max_length=64),
        ),
        migrations.AddField(
            model_name='telegrambotconfig',
            name='require_contact_details',
            field=models.BooleanField(default=False, help_text='Whether buyer bot requires delivery contact details before browsing.'),
        ),
        migrations.AddField(
            model_name='telegrambotconfig',
            name='require_password',
            field=models.BooleanField(default=False, help_text='Whether this bot requires a password for access.'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='contact_details',
            field=models.TextField(blank=True, default='', help_text='Buyer/user delivery contact details (Name, Email, Contact No, Address).'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_authorized',
            field=models.BooleanField(default=False, help_text='Whether the user has entered the access password (if required).'),
        ),
    ]
