# Generated by Django 5.2.17 on 2026-09-27 07:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('starting_price', models.DecimalField(decimal_places=2, help_text='Minimum opening bid price.', max_digits=12)),
                ('bid_increment', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Minimum monetary step required between bids.', max_digits=12)),
                ('current_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Highest current valid bid amount, or 0.00 if no bids placed.', max_digits=12)),
                ('buy_now_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional price to instantly purchase and close the auction.', max_digits=12, null=True)),
                ('start_at', models.DateTimeField(db_index=True, help_text='Scheduled UTC datetime when bidding begins.')),
                ('end_at', models.DateTimeField(db_index=True, help_text='Scheduled UTC datetime when bidding ends.')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active / Open'), ('CLOSED', 'Closed'), ('SOLD', 'Sold'), ('UNSOLD', 'Unsold'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', help_text='Current operational state of the auction.', max_length=20)),
                ('winner_id', models.CharField(blank=True, db_index=True, help_text='Headless identifier of the winning bidder upon close.', max_length=100, null=True)),
                ('winning_price', models.DecimalField(blank=True, decimal_places=2, help_text='Final winning hammer price.', max_digits=12, null=True)),
                ('is_reminder_sent', models.BooleanField(default=False, help_text='Flag indicating whether the 15-minute close reminder was dispatched.')),
            ],
            options={
                'verbose_name': 'Auction',
                'verbose_name_plural': 'Auctions',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('bidder_id', models.CharField(db_index=True, help_text='Headless identifier of the bidding participant.', max_length=100)),
                ('bidder_name', models.CharField(blank=True, help_text='Display handle or name of the bidder.', max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monetary amount of this bid.', max_digits=12)),
                ('placed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the bid was registered.')),
            ],
            options={
                'verbose_name': 'Bid',
                'verbose_name_plural': 'Bids',
                'ordering': ['-amount', '-placed_at'],
            },
        ),
    ]
