# Generated by Django 5.2.17 on 2026-09-27 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidding', '0001_initial'),
        ('listings', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='listing',
            field=models.OneToOneField(help_text='The underlying catalog item being auctioned.', on_delete=django.db.models.deletion.PROTECT, related_name='auction', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='auction',
            name='tenant',
            field=models.ForeignKey(help_text='Mandatory explicit foreign key to the owning Tenant.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(help_text='The auction receiving this bid.', on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='bidding.auction'),
        ),
        migrations.AddField(
            model_name='bid',
            name='tenant',
            field=models.ForeignKey(help_text='Mandatory explicit foreign key to the owning Tenant.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='auction',
            name='highest_bid',
            field=models.ForeignKey(blank=True, help_text='Reference to the current leading bid.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bidding.bid'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction', '-amount', '-placed_at'], name='bid_auction_rank_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['tenant', 'bidder_id'], name='bid_tenant_bidder_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['tenant', 'status', 'end_at'], name='auction_tenant_status_end_idx'),
        ),
    ]
