# Generated by Django 5.2.17 on 2026-09-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='anti_sniping_seconds',
            field=models.PositiveIntegerField(default=120, help_text='Window in seconds before end_at where incoming bids trigger an extension.'),
        ),
        migrations.AddField(
            model_name='auction',
            name='extension_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of anti-sniping extensions applied to this auction.'),
        ),
        migrations.AddField(
            model_name='auction',
            name='extension_seconds',
            field=models.PositiveIntegerField(default=120, help_text='Duration in seconds to extend end_at when anti-sniping triggers.'),
        ),
        migrations.AddField(
            model_name='bid',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Unique client-provided key ensuring idempotent bid submission.', max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['tenant', 'auction', 'idempotency_key'], name='bid_tenant_idempotency_idx'),
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('tenant', 'auction', 'idempotency_key'), name='unique_tenant_auction_idempotency_key'),
        ),
    ]
