# Generated by Django 5.2.17 on 2026-09-27 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_auction_anti_sniping_seconds_auction_extension_count_and_more'),
        ('listings', '0002_listingimage_seller'),
        ('telegram_engine', '0003_telegrambotconfig_access_password_and_more'),
        ('tenants', '0004_remove_tenant_admin_initial_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('listing', models.ForeignKey(help_text='Favorited catalog listing.', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_entries', to='listings.listing')),
                ('telegram_user', models.ForeignKey(help_text='User who added the item to their favorites.', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='telegram_engine.telegramuser')),
                ('tenant', models.ForeignKey(help_text='Mandatory explicit foreign key to the owning Tenant.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Buyer Wishlist Item',
                'verbose_name_plural': 'Buyer Wishlist Items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'telegram_user'], name='bidding_buy_tenant__658336_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'telegram_user', 'listing'), name='unique_tenant_user_listing_wishlist')],
            },
        ),
    ]
