# Generated by Django 5.2.17 on 2026-09-27 08:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(db_index=True, help_text='Tenant-scoped identifier for owner (e.g. Telegram ID or SYSTEM)', max_length=128)),
                ('account_type', models.CharField(choices=[('USER_WALLET', 'User Wallet'), ('PLATFORM_CASH', 'Platform Cash Account'), ('PLATFORM_REVENUE', 'Platform Revenue Account'), ('ESCROW', 'Escrow Account'), ('COMMISSION', 'Commission Account')], db_index=True, default='USER_WALLET', max_length=32)),
                ('currency', models.CharField(db_index=True, default='INR', help_text='ISO 4217 Currency Code', max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=20)),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Materialized available balance. Authoritative truth derives from ledger.', max_digits=14)),
                ('held_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Materialized held/reserved balance.', max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='Mandatory explicit foreign key to the owning Tenant.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('BID_HOLD', 'Bid Hold'), ('BID_RELEASE', 'Bid Release'), ('PURCHASE', 'Purchase'), ('REFUND', 'Refund'), ('COMMISSION', 'Commission'), ('FEE', 'Fee'), ('ADJUSTMENT', 'Adjustment'), ('REVERSAL', 'Reversal'), ('TRANSFER', 'Transfer')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], db_index=True, default='COMPLETED', max_length=20)),
                ('reference_type', models.CharField(blank=True, db_index=True, default='', help_text='Domain entity type (e.g. AUCTION, BID, DEPOSIT)', max_length=64)),
                ('reference_id', models.CharField(blank=True, db_index=True, default='', help_text='Domain entity identifier', max_length=128)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='Unique caller-supplied token to prevent duplicate operations', max_length=255, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(help_text='Mandatory explicit foreign key to the owning Tenant.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Strictly positive monetary amount.', max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='finance.financialaccount')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='finance.ledgertransaction')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['tenant', 'owner_id'], name='finance_fin_tenant__7b1130_idx'),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['tenant', 'account_type'], name='finance_fin_tenant__a66845_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.UniqueConstraint(fields=('tenant', 'owner_id', 'account_type', 'currency'), name='unique_tenant_owner_account_currency'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['tenant', 'reference_type', 'reference_id'], name='finance_led_tenant__d31aab_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['tenant', 'created_at'], name='finance_led_tenant__e11289_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgertransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('tenant', 'idempotency_key'), name='unique_tenant_idempotency_key'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', 'created_at'], name='finance_led_account_8445ca_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['transaction', 'entry_type'], name='finance_led_transac_25cdb6_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='positive_ledger_entry_amount'),
        ),
    ]
