# Generated by Django 5.2.17 on 2026-10-03 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('tenants', '0004_remove_tenant_admin_initial_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProofRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('telegram_user_id', models.CharField(db_index=True, max_length=128)),
                ('telegram_username', models.CharField(blank=True, default='', max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='MYR', max_length=3)),
                ('proof_image', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('admin_notes', models.CharField(blank=True, default='', max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, default='', max_length=150)),
                ('tenant', models.ForeignKey(help_text='Mandatory explicit foreign key to the owning Tenant.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', 'telegram_user_id'], name='finance_dep_tenant__229ba5_idx'), models.Index(fields=['tenant', 'created_at'], name='finance_dep_tenant__3bcefd_idx')],
            },
        ),
    ]
