# Generated by Django 5.2.17 on 2026-09-27 07:22

import apps.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable tenant or organization name (e.g., 'CYG Malaysia', 'AquaBid Australia').", max_length=100)),
                ('slug', models.SlugField(help_text="Unique URL and subdomain identifier (e.g., 'cyg', 'aquabid', 'australia').", unique=True)),
                ('code', models.CharField(db_index=True, help_text="Unique uppercase country or region code (e.g., 'MY', 'AU', 'NZ').", max_length=10, unique=True)),
                ('country', models.CharField(help_text='Primary country of operations.', max_length=100)),
                ('timezone', models.CharField(default='UTC', help_text="Standard IANA timezone string (e.g., 'Australia/Sydney', 'Asia/Kuala_Lumpur').", max_length=64, validators=[apps.tenants.models.validate_iana_timezone])),
                ('currency', models.CharField(default='USD', help_text="Standard 3-letter ISO 4217 currency code (e.g., 'AUD', 'MYR', 'USD').", max_length=3)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Controls whether this tenant is operational and accepting traffic.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the tenant was registered.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the tenant configuration was last modified.')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'code'], name='tenant_active_code_idx')],
            },
        ),
    ]
