# Generated by Django 5.2.17 on 2026-09-27 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PLATFORM_ADMIN', 'Platform Administrator'), ('TENANT_ADMIN', 'Tenant Administrator'), ('TENANT_STAFF', 'Tenant Staff')], db_index=True, default='TENANT_STAFF', help_text='Administrative role within the tenant.', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this membership is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the membership was granted.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the membership was last updated.')),
                ('tenant', models.ForeignKey(help_text='Tenant organization.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
                ('user', models.ForeignKey(help_text='User belonging to the tenant.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant Membership',
                'verbose_name_plural': 'Tenant Memberships',
                'indexes': [models.Index(fields=['user', 'is_active', 'role'], name='tenants_ten_user_id_c90054_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'tenant'), name='unique_user_tenant_membership')],
            },
        ),
    ]
