# Generated by Django 5.2.17 on 2026-09-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='admin_initial_password',
            field=models.CharField(blank=True, help_text='Initial admin password visible to Super Admin for credentials handover.', max_length=128),
        ),
        migrations.AddField(
            model_name='tenant',
            name='admin_username',
            field=models.CharField(blank=True, help_text='Primary administrative account username for this tenant.', max_length=150),
        ),
    ]
