# Generated by Django on 2026-09-28
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_admin_initial_password_tenant_admin_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='admin_initial_password',
        ),
    ]
