# Generated by Django 5.2.17 on 2026-10-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_remove_tenant_admin_initial_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Tenant configuration metadata, fee schedules, bank details, etc.'),
        ),
    ]
