# Generated by Django 5.2.17 on 2026-09-27 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('seller_id', models.CharField(db_index=True, help_text='External/headless identifier for the seller.', max_length=100)),
                ('seller_username', models.CharField(blank=True, help_text='Optional display handle of the seller.', max_length=150)),
                ('title', models.CharField(help_text='Headline or title of the listing.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Comprehensive item description and terms.')),
                ('category', models.CharField(blank=True, db_index=True, default='General', help_text='Taxonomy category for the listing.', max_length=100)),
                ('listing_type', models.CharField(choices=[('AUCTION', 'Auction'), ('BUY_NOW', 'Buy It Now')], db_index=True, default='AUCTION', help_text='Format: Auction or Buy It Now.', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], db_index=True, default='PENDING', help_text='Current moderation/lifecycle status.', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Total units available at creation.')),
                ('remaining_quantity', models.PositiveIntegerField(default=1, help_text='Units currently remaining unsold.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extensible key-value metadata (e.g. breed, size, shipping, location).')),
                ('tenant', models.ForeignKey(help_text='Mandatory explicit foreign key to the owning Tenant.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', 'listing_type'], name='listing_tenant_status_type_idx'), models.Index(fields=['tenant', 'seller_id'], name='listing_tenant_seller_idx')],
            },
        ),
    ]
