# Generated by Django 5.2.17 on 2026-09-27 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        ('telegram_engine', '0001_initial'),
        ('tenants', '0004_remove_tenant_admin_initial_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('image', models.ImageField(blank=True, help_text='Local/cloud stored image asset.', null=True, upload_to='listings/%Y/%m/')),
                ('file_url', models.CharField(blank=True, default='', help_text='Direct URL to media file if stored externally or relative path.', max_length=500)),
                ('telegram_file_id', models.CharField(blank=True, default='', help_text='Telegram file_id for quick re-serving or downloading.', max_length=255)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in gallery.')),
                ('listing', models.ForeignKey(help_text='Parent listing.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
                ('tenant', models.ForeignKey(help_text='Mandatory explicit foreign key to the owning Tenant.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Listing Image',
                'verbose_name_plural': 'Listing Images',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['tenant', 'listing'], name='listings_li_tenant__903b8e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('seller_id', models.CharField(db_index=True, help_text='External/headless identifier for the seller (e.g. str(telegram_user_id)).', max_length=100)),
                ('business_name', models.CharField(help_text='Trading name, farm name, or individual seller brand.', max_length=150)),
                ('contact_name', models.CharField(help_text='Full legal or representative name of contact person.', max_length=150)),
                ('phone', models.CharField(help_text='Contact telephone / WhatsApp number.', max_length=50)),
                ('email', models.EmailField(blank=True, default='', help_text='Contact email address.', max_length=254)),
                ('address', models.TextField(blank=True, default='', help_text='Physical farm or dispatch address.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REJECTED', 'Rejected')], db_index=True, default='ACTIVE', help_text='Seller onboarding and moderation status.', max_length=20)),
                ('telegram_user', models.ForeignKey(help_text='Telegram account linked to this seller profile.', on_delete=django.db.models.deletion.CASCADE, related_name='seller_profiles', to='telegram_engine.telegramuser')),
                ('tenant', models.ForeignKey(help_text='Mandatory explicit foreign key to the owning Tenant.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='listings_se_tenant__26ec63_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'telegram_user'), name='unique_tenant_seller_telegram_user'), models.UniqueConstraint(fields=('tenant', 'seller_id'), name='unique_tenant_seller_id')],
            },
        ),
    ]
